print('Welcome to Anonymous Archives. Please we need your details to continue')
Name=input("ENTER YOUR NAME ")
print("Hello "+Name) 
Birth_year=input("Enter your birth year ")
Age=2023-int(Birth_year)
print (Age)
print ("Welcome ",Name, "to anonymous archives where the books of our dreams exist in a matter of hidden folds")
username=input('enter your prefered username ')
print('Since you are',Age,'we think you would like the premium package of our services')
genre=input('A genres of books you like ')
print('Since you like',genre ,username,'We hope you would like,Anonymous, Magnogravity')
print=('Thanks for your support')